In [2]:
import torch
import jax
from jax import numpy as jnp

In [11]:
#Prove that the transpose of the transpose of a matrix is the matrix itself: 
v = jnp.ones((3,3))
v.T.T == v

Array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [16]:
# Given two matrices and , show that sum and transposition commute
A = torch.randn((3,3))
B = torch.randn((3,3))

A.T + B.T == (A+B).T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [18]:
# Given any square matrix ,A+A.T is always symmetric? Can you prove the result by using only the results of the previous two exercises
A + A.T  == (A + A.T).T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [19]:
# We defined the tensor X of shape (2, 3, 4) in this section. What is the output of len(X)? Write your answer without implementing any code, then check your answer using code.
X = torch.arange(24).reshape(2, 3, 4)
len(X)

2

In [20]:
# Run A / A.sum(axis=1) and see what happens. Can you analyze the results?
X/X.sum(axis=1)


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [23]:
for i in range(3):
    print(i, X.sum(axis=i).shape)

0 torch.Size([3, 4])
1 torch.Size([2, 4])
2 torch.Size([2, 3])


In [25]:
# Feed a tensor with three or more axes to the linalg.norm function and observe its output
torch.norm(A)

tensor(3.4255)

In [3]:
import os
import psutil
import time
import gc

def process_memory():
    process = psutil.Process(os.getpid())
    mem_info = process.memory_info()
    return mem_info.rss

    

A = torch.randn((2**5, 2**8))
B = torch.randn((2**8, 2**5))
C = torch.randn((2**5, 2**8))

mem_before = process_memory()
start = time.time()
y = (A@B)@C
mem_after = process_memory()
mem_diff = mem_after - mem_before
exec_time = time.time() - start
print(f"Memory difference: {mem_diff/(1024*1024)} megabytes")
print(f"time taken: {exec_time}")
del A
gc.collect()
print("******")
A = torch.randn((2**5, 2**8))
B = torch.randn((2**8, 2**5))
C = torch.randn((2**5, 2**8))
mem_before = process_memory()
start = time.time()
y = A@(B@C)
mem_after = process_memory()
mem_diff = mem_after - mem_before
exec_time = time.time() - start

print(f"Memory difference: {mem_diff/(1024*1024)} megabytes")
print(f"time taken: {exec_time}")


Memory difference: 1.67578125 megabytes
time taken: 0.003594636917114258
******
Memory difference: 0.69921875 megabytes
time taken: 0.0004830360412597656


In [4]:
A@B

tensor([[ 22.3466, -13.7510, -27.3286,  ...,   4.7721, -31.7303,  -0.4962],
        [-16.2436,  24.1385,  -1.9065,  ...,   0.7895, -29.1300, -12.5318],
        [ -6.5032,  -0.1007,   9.3973,  ...,  -3.2985,   6.1022,  31.3605],
        ...,
        [  3.9329,  23.5765,  -3.7415,  ..., -36.2057,  14.8663,  13.6330],
        [ -3.1952,   0.5317, -21.2134,  ...,  -9.1665,   0.1057,  -1.2638],
        [ -6.9737, -11.0558,   9.9862,  ...,   6.5451,   9.3291,  -1.1995]])

In [5]:
A.shape, C.T.shape

(torch.Size([32, 256]), torch.Size([256, 32]))

In [6]:
A@C.T

tensor([[ 10.0090,  -1.9095, -16.0520,  ...,  -8.7113,  27.4236, -28.6053],
        [ -4.7046,   5.9514,   7.5451,  ..., -17.4480,  32.9090,  11.2259],
        [-10.6740,  10.3164,  25.5560,  ...,   6.7556,  -0.5554,  21.3093],
        ...,
        [ -2.7766,  -1.9944, -30.3462,  ..., -20.4943,  21.3764, -11.1675],
        [-35.3743, -15.2393,  14.1361,  ...,   7.3302,   5.9985,  -5.1945],
        [ -3.4585,   3.0254,  10.4838,  ..., -15.5326,   3.5561,  -4.9475]])